DOWNLOAD_METHOD_BITTORRENT = 0
DOWNLOAD_METHOD_UNICAST = 1
DOWNLOAD_METHOD_BITTORRENT_NAME = 'bittorrent'
DOWNLOAD_METHOD_UNICAST_NAME = 'unicast'

HYPERVISOR_TYPE_XEN = 0
HYPERVISOR_TYPE_KVM = 1

SERVICE_GENTOO = 0
SERVICE_UBUNTU = 1
SERVICE_HADOOP = 2
SERVICE_APACHE = 3

PROTOTYPE_GENTOO = 0
PROTOTYPE_UBUNTU_12_04 = 1
PROTOTYPE_HADOOP_MASTER = 2
PROTOTYPE_HADOOP_SLAVE = 3
PROTOTYPE_APACHE = 4
PROTOTYPE_UBUNTU_9_04 = 5

KERNEL_VERSION_3_7 = 0
KERNEL_VERSION_2_6 = 1
KERNEL_DEFAULT = KERNEL_VERSION_3_7
